#! /usr/bin/env bash

# Builds the deployment environment Docker image

set -e
set +x

readonly SHORT_SHA="$(git rev-parse --short HEAD)"
readonly DATE_IN_UNIX_SECONDS="$(date +%s)"
readonly SNAPSHOT_TAG="SNAPSHOT-${SHORT_SHA}-${DATE_IN_UNIX_SECONDS}"
readonly IMAGE="deployment-env"

PLATFORM_ARG=()
if [[ -n "${PLATFORM}" ]]; then
  PLATFORM_ARG=(--platform "${PLATFORM}")
fi
readonly PLATFORM_ARG

echo "start ${IMAGE} build"
docker buildx create --use
docker buildx build --push \
  "${PLATFORM_ARG[@]}" \
  -t "docker.io/civiform/${IMAGE}:latest" \
  -t "docker.io/civiform/${IMAGE}:${SNAPSHOT_TAG}" \
  -f development.Dockerfile .
