apiVersion: v1
kind: Service
metadata:
  name: civiform-server-tenant-{{ .Values.tenantId }}
  namespace: ns-tenant-{{ .Values.tenantId }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: civiform-server-{{ .Values.tenantId }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civiform-server-ingress-{{ .Values.tenantId }}
  namespace: ns-tenant-{{ .Values.tenantId }}
  # annotations:
  # uncomment to only allow https traffic
  #   kubernetes.io/ingress.allow-http: "false"
spec:
  # tls:
  # - secretName: SECRET_NAME

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: civiform-server-tenant-{{ .Values.tenantId }}
            port:
              number: 80
      # host: {{ .Values.publicSubdomain }}
