#!/usr/bin/expect

set timeout -1
spawn /aws-nuke --config $env(GITHUB_WORKSPACE)/cloud-deploy-infra/tests/nuke.yaml --no-dry-run
expect "Do you want to continue? Enter account alias to continue."
send "civiform-cloud-deploy-infra-tests-0\n"
expect {
	"Do you want to continue? Enter account alias to continue." { send "civiform-cloud-deploy-infra-tests-0\n" }
	"No resource to delete" exit
}
expect {
	"Nuke complete" exit
}
