#! /usr/bin/env bash

# Builds the prometheus metrics scraper Docker image

set -e
set +x

# This is the snapshot from last year that works as expected
readonly SNAPSHOT_TAG="SNAPSHOT-ef53299-1701983458"
readonly IMAGE="aws-metrics-scraper"
readonly FULL_IMAGE_NAME="docker.io/civiform/${IMAGE}:${SNAPSHOT_TAG}"
readonly LATEST_IMAGE_NAME="docker.io/civiform/${IMAGE}:latest"

echo "Pulling snapshot image: ${FULL_IMAGE_NAME}"
docker pull "${FULL_IMAGE_NAME}"

echo "Tagging snapshot as latest: ${FULL_IMAGE_NAME} -> ${LATEST_IMAGE_NAME}"
docker tag "${FULL_IMAGE_NAME}" "${LATEST_IMAGE_NAME}"

echo "Pushing latest tag: ${LATEST_IMAGE_NAME}"
docker push "${LATEST_IMAGE_NAME}"

echo "Complete"
