name: AWS Staging Deploy
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
on: 
  workflow_dispatch: {}
  schedule:
    - cron: 0 */12 * * * # “At minute 0 past every 12th hour.”

concurrency:
  group: stagingenvironment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SKIP_CONFIRMATIONS: true # for terraform
      CF_SKIP_WARN: true # for resolving git commit
    steps:
      - name: check out branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: resolve latest snapshot tag
        run: source bin/resolve-latest-snapshot-tag

      - name: Run deployment with latest
        run: bin/deploy --tag=${LATEST_SNAPSHOT_TAG} --config_file="aws_staging_civiform_config.sh"

      - name: Run Prober tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 50
          max_attempts: 2
          retry_wait_seconds: 30
          command: bin/run-prober "https://staging-aws.civiform.dev"
