name: Deploy Azure Staging
on:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}
  schedule:
    - cron: 0 */12 * * * # “At minute 0 past every 12th hour.”
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
      SKIP_CONFIRMATIONS: true # for terraform
      CF_SKIP_WARN: true # for resolving git commit
    steps:
      - name: check out branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: login to Azure
        run: bin/azure-cli-login

      - name: resolve latest snapshot tag
        run: source bin/resolve-latest-snapshot-tag

      - name: Run deployment with latest
        run: bin/deploy --tag=${LATEST_SNAPSHOT_TAG} --config_file="aws_staging_civiform_config.sh"
