# Note: this was built to help in deploying on Windows, but we currently don't have Windows deployers, so we're disabling it for now.

name: build_push_deployment_env_image

on:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: {}

permissions: read-all

# Build and push the deployment env image.
jobs:
  build_deployment_env:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: Build deployment env
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #- id: file_changes
      #  uses: tj-actions/changed-files@v45
      #  with:
      #    json: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3
      - name: Run build
        id: build_and_push_deployment_env
        env:
          DOCKER_BUILDKIT: 1
          PLATFORM: 'linux/amd64'
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        #if: contains(toJSON(steps.file_changes.outputs.all_changed_files), 'cloud/aws/deployment/')
        run: |
          cd $GITHUB_WORKSPACE/cloud/aws/deployment
          ./build-deployment
